CREATE TYPE "public"."account_type" AS ENUM('live', 'demo', 'paper');--> statement-breakpoint
CREATE TYPE "public"."emotional_state" AS ENUM('confident', 'fearful', 'greedy', 'neutral', 'frustrated', 'excited', 'anxious');--> statement-breakpoint
CREATE TYPE "public"."execution_type" AS ENUM('entry', 'exit', 'scale_in', 'scale_out');--> statement-breakpoint
CREATE TYPE "public"."import_source" AS ENUM('manual', 'csv');--> statement-breakpoint
CREATE TYPE "public"."instrument_type" AS ENUM('futures', 'forex');--> statement-breakpoint
CREATE TYPE "public"."trade_direction" AS ENUM('long', 'short');--> statement-breakpoint
CREATE TYPE "public"."trade_status" AS ENUM('open', 'closed');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "edgejournal_account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"broker" text,
	"account_type" "account_type" DEFAULT 'live' NOT NULL,
	"initial_balance" numeric(20, 2) DEFAULT '0',
	"currency" text DEFAULT 'USD',
	"account_number" text,
	"is_active" boolean DEFAULT true,
	"is_default" boolean DEFAULT false,
	"notes" text,
	"color" text DEFAULT '#6366f1',
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "edgejournal_ai_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_ai_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"title" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "edgejournal_ai_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_ai_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversation_id" integer NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "edgejournal_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"color" text DEFAULT '#6366f1',
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "edgejournal_trade_execution" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_trade_execution_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trade_id" integer NOT NULL,
	"execution_type" "execution_type" NOT NULL,
	"price" numeric(20, 8) NOT NULL,
	"quantity" numeric(20, 8) NOT NULL,
	"executed_at" timestamp with time zone NOT NULL,
	"fees" numeric(20, 2) DEFAULT '0',
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "edgejournal_trade_screenshot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_trade_screenshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"trade_id" integer NOT NULL,
	"url" text NOT NULL,
	"caption" text,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "edgejournal_trade_tag" (
	"trade_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "edgejournal_trade_tag_trade_id_tag_id_pk" PRIMARY KEY("trade_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE "edgejournal_trade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_trade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"account_id" integer,
	"symbol" text NOT NULL,
	"instrument_type" "instrument_type" NOT NULL,
	"direction" "trade_direction" NOT NULL,
	"status" "trade_status" DEFAULT 'open' NOT NULL,
	"entry_price" numeric(20, 8) NOT NULL,
	"entry_time" timestamp with time zone NOT NULL,
	"exit_price" numeric(20, 8),
	"exit_time" timestamp with time zone,
	"quantity" numeric(20, 8) NOT NULL,
	"stop_loss" numeric(20, 8),
	"take_profit" numeric(20, 8),
	"stop_loss_hit" boolean DEFAULT false,
	"take_profit_hit" boolean DEFAULT false,
	"realized_pnl" numeric(20, 2),
	"fees" numeric(20, 2) DEFAULT '0',
	"net_pnl" numeric(20, 2),
	"setup_type" text,
	"emotional_state" "emotional_state",
	"notes" text,
	"import_source" "import_source" DEFAULT 'manual' NOT NULL,
	"external_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "edgejournal_user_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_user_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"openai_api_key" text,
	"anthropic_api_key" text,
	"google_api_key" text,
	"preferred_ai_provider" text DEFAULT 'openai',
	"default_instrument_type" "instrument_type" DEFAULT 'futures',
	"timezone" text DEFAULT 'UTC',
	"currency" text DEFAULT 'USD',
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "edgejournal_user_settings_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "edgejournal_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "edgejournal_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clerk_id" text NOT NULL,
	"email" text NOT NULL,
	"name" text,
	"image_url" text,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "edgejournal_user_clerk_id_unique" UNIQUE("clerk_id")
);
--> statement-breakpoint
ALTER TABLE "edgejournal_account" ADD CONSTRAINT "edgejournal_account_user_id_edgejournal_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."edgejournal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_ai_conversation" ADD CONSTRAINT "edgejournal_ai_conversation_user_id_edgejournal_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."edgejournal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_ai_message" ADD CONSTRAINT "edgejournal_ai_message_conversation_id_edgejournal_ai_conversation_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."edgejournal_ai_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_tag" ADD CONSTRAINT "edgejournal_tag_user_id_edgejournal_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."edgejournal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade_execution" ADD CONSTRAINT "edgejournal_trade_execution_trade_id_edgejournal_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."edgejournal_trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade_screenshot" ADD CONSTRAINT "edgejournal_trade_screenshot_trade_id_edgejournal_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."edgejournal_trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade_tag" ADD CONSTRAINT "edgejournal_trade_tag_trade_id_edgejournal_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."edgejournal_trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade_tag" ADD CONSTRAINT "edgejournal_trade_tag_tag_id_edgejournal_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."edgejournal_tag"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade" ADD CONSTRAINT "edgejournal_trade_user_id_edgejournal_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."edgejournal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_trade" ADD CONSTRAINT "edgejournal_trade_account_id_edgejournal_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."edgejournal_account"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "edgejournal_user_settings" ADD CONSTRAINT "edgejournal_user_settings_user_id_edgejournal_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."edgejournal_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "edgejournal_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "account_is_default_idx" ON "edgejournal_account" USING btree ("is_default");--> statement-breakpoint
CREATE INDEX "conversation_user_id_idx" ON "edgejournal_ai_conversation" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "message_conversation_id_idx" ON "edgejournal_ai_message" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "tag_user_id_idx" ON "edgejournal_tag" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "execution_trade_id_idx" ON "edgejournal_trade_execution" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "screenshot_trade_id_idx" ON "edgejournal_trade_screenshot" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_tag_trade_id_idx" ON "edgejournal_trade_tag" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_tag_tag_id_idx" ON "edgejournal_trade_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "trade_user_id_idx" ON "edgejournal_trade" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "trade_account_id_idx" ON "edgejournal_trade" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "trade_symbol_idx" ON "edgejournal_trade" USING btree ("symbol");--> statement-breakpoint
CREATE INDEX "trade_entry_time_idx" ON "edgejournal_trade" USING btree ("entry_time");--> statement-breakpoint
CREATE INDEX "trade_status_idx" ON "edgejournal_trade" USING btree ("status");--> statement-breakpoint
CREATE INDEX "user_clerk_id_idx" ON "edgejournal_user" USING btree ("clerk_id");