CREATE TYPE "public"."challenge_status" AS ENUM('active', 'passed', 'failed');--> statement-breakpoint
CREATE TYPE "public"."drawdown_type" AS ENUM('trailing', 'static', 'eod');--> statement-breakpoint
CREATE TYPE "public"."payout_frequency" AS ENUM('weekly', 'bi_weekly', 'monthly');--> statement-breakpoint
CREATE TABLE "account_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"color" text DEFAULT '#6366f1',
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "max_drawdown" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "drawdown_type" "drawdown_type";--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "daily_loss_limit" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "profit_target" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "consistency_rule" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "min_trading_days" integer;--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "challenge_start_date" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "challenge_end_date" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "challenge_status" "challenge_status";--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "profit_split" numeric(10, 2);--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "payout_frequency" "payout_frequency";--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "linked_account_id" integer;--> statement-breakpoint
ALTER TABLE "account" ADD COLUMN "group_id" integer;--> statement-breakpoint
ALTER TABLE "account_group" ADD CONSTRAINT "account_group_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_group_user_id_idx" ON "account_group" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_group_id_account_group_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."account_group"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_group_id_idx" ON "account" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "account_linked_account_id_idx" ON "account" USING btree ("linked_account_id");--> statement-breakpoint
-- Update existing account types: 'paper' -> 'demo', keep 'live' and 'demo'
UPDATE "public"."account" SET "account_type" = 'demo' WHERE "account_type" = 'paper';--> statement-breakpoint
-- Remove default before altering column type
ALTER TABLE "public"."account" ALTER COLUMN "account_type" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "public"."account" ALTER COLUMN "account_type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."account_type";--> statement-breakpoint
CREATE TYPE "public"."account_type" AS ENUM('prop_challenge', 'prop_funded', 'live', 'demo');--> statement-breakpoint
ALTER TABLE "public"."account" ALTER COLUMN "account_type" SET DATA TYPE "public"."account_type" USING "account_type"::"public"."account_type";--> statement-breakpoint
ALTER TABLE "public"."account" ALTER COLUMN "account_type" SET DEFAULT 'live';
