-- Add daily_notes table for trading diary feature
CREATE TABLE IF NOT EXISTS "edgejournal_daily_note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"user_id" integer NOT NULL REFERENCES "edgejournal_user"("id") ON DELETE CASCADE,
	"account_id" integer REFERENCES "edgejournal_account"("id") ON DELETE SET NULL,
	"date" timestamp with time zone NOT NULL,
	"pre_market_notes" text,
	"market_outlook" text,
	"planned_setups" text,
	"post_market_notes" text,
	"lessons_learned" text,
	"emotional_state" "emotional_state",
	"day_rating" integer,
	"daily_goal" text,
	"goal_met" boolean,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone
);

-- Add indexes
CREATE INDEX IF NOT EXISTS "daily_note_user_id_idx" ON "edgejournal_daily_note" ("user_id");
CREATE INDEX IF NOT EXISTS "daily_note_date_idx" ON "edgejournal_daily_note" ("date");
CREATE INDEX IF NOT EXISTS "daily_note_account_id_idx" ON "edgejournal_daily_note" ("account_id");
