CREATE TABLE "filter_preset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "filter_preset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"filters" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "rating" integer;--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "is_reviewed" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "user_settings" ADD COLUMN "trade_log_columns" text;--> statement-breakpoint
ALTER TABLE "filter_preset" ADD CONSTRAINT "filter_preset_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "filter_preset_user_id_idx" ON "filter_preset" USING btree ("user_id");