CREATE TYPE "public"."playbook_rule_category" AS ENUM('entry', 'exit', 'risk', 'management');--> statement-breakpoint
CREATE TABLE "playbook_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playbook_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playbook_id" integer NOT NULL,
	"text" text NOT NULL,
	"category" "playbook_rule_category" DEFAULT 'entry' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "playbook" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "playbook_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"color" text DEFAULT '#d4ff00',
	"entry_criteria" text,
	"exit_rules" text,
	"risk_parameters" text,
	"scaling_rules" text,
	"trailing_rules" text,
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "trade_rule_check" (
	"trade_id" integer NOT NULL,
	"rule_id" integer NOT NULL,
	"checked" boolean DEFAULT false NOT NULL,
	"checked_at" timestamp with time zone,
	CONSTRAINT "trade_rule_check_trade_id_rule_id_pk" PRIMARY KEY("trade_id","rule_id")
);
--> statement-breakpoint
ALTER TABLE "trade" ADD COLUMN "playbook_id" integer;--> statement-breakpoint
ALTER TABLE "playbook_rule" ADD CONSTRAINT "playbook_rule_playbook_id_playbook_id_fk" FOREIGN KEY ("playbook_id") REFERENCES "public"."playbook"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "playbook" ADD CONSTRAINT "playbook_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_rule_check" ADD CONSTRAINT "trade_rule_check_trade_id_trade_id_fk" FOREIGN KEY ("trade_id") REFERENCES "public"."trade"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "trade_rule_check" ADD CONSTRAINT "trade_rule_check_rule_id_playbook_rule_id_fk" FOREIGN KEY ("rule_id") REFERENCES "public"."playbook_rule"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "playbook_rule_playbook_id_idx" ON "playbook_rule" USING btree ("playbook_id");--> statement-breakpoint
CREATE INDEX "playbook_rule_category_idx" ON "playbook_rule" USING btree ("category");--> statement-breakpoint
CREATE INDEX "playbook_user_id_idx" ON "playbook" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "playbook_is_active_idx" ON "playbook" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "trade_rule_check_trade_id_idx" ON "trade_rule_check" USING btree ("trade_id");--> statement-breakpoint
CREATE INDEX "trade_rule_check_rule_id_idx" ON "trade_rule_check" USING btree ("rule_id");--> statement-breakpoint
CREATE INDEX "trade_playbook_id_idx" ON "trade" USING btree ("playbook_id");